import test from "node:test";import assert from "node:assert/strict";import {ValidatorRegistry} from "../src/core/index.js";import {JsonValidator,HtmlValidator,validateArtifact} from "../src/verification/index.js";import {ExternalOperationLedger} from "../src/publishing/index.js";import {createSnapshot,verifySnapshot} from "../src/research/snapshots.js";import {validateCitation} from "../src/research/citations.js";import {HtmlRenderer,MarkdownRenderer,JsonDocumentRenderer,RendererRegistry} from "../src/documents/index.js";import {MemoryObjectStore} from "../src/adapters/index.js";import {ContentAddressedStore} from "../src/storage/index.js";
test("validator registry validates real JSON bytes",async()=>{const r=new ValidatorRegistry();r.register(JsonValidator);assert.equal((await validateArtifact(r,"application/json",new TextEncoder().encode('{"x":1}'))).passed,true);assert.equal((await validateArtifact(r,"application/json",new TextEncoder().encode('{'))).passed,false)});
test("HTML render then validator passes",async()=>{const bytes=(await new HtmlRenderer().render({title:"T",sections:[{heading:"H",body:"B"}]})).bytes;const r=new ValidatorRegistry();r.register(HtmlValidator);assert.equal((await validateArtifact(r,"text/html",bytes)).passed,true)});
test("unknown artifact type cannot be called verified",async()=>{assert.equal((await validateArtifact(new ValidatorRegistry(),"application/pdf",new Uint8Array())).passed,false)});
test("external operation is idempotent and preserves success",()=>{const l=new ExternalOperationLedger();const a=l.begin({idempotencyKey:"k",provider:"store",operation:"publish"});const b=l.begin({idempotencyKey:"k",provider:"store",operation:"publish"});assert.equal(a,b);l.succeed("k","external-1");assert.equal(l.begin({idempotencyKey:"k",provider:"store",operation:"publish"}).externalId,"external-1");assert.throws(()=>l.fail("k","late failure"))});
test("research snapshot detects mutation",()=>{const s=createSnapshot("u","t","body","now");assert.equal(verifySnapshot(s),true);s.text="changed";assert.equal(verifySnapshot(s),false)});
test("citation quote must exist in snapshot text",()=>{assert.equal(validateCitation({claimId:"c",snapshotDigest:"d",quote:"fact"},"the fact here").pass,true);assert.equal(validateCitation({claimId:"c",snapshotDigest:"d",quote:"missing"},"the fact here").pass,false)});
test("renderer registry supports HTML Markdown JSON",()=>{const r=new RendererRegistry();r.register(new HtmlRenderer());r.register(new MarkdownRenderer());r.register(new JsonDocumentRenderer());assert.deepEqual(r.formats().sort(),["HTML","JSON","MARKDOWN"])});
test("content addressed store dedupes by digest and verifies bytes",async()=>{const cas=new ContentAddressedStore(new MemoryObjectStore());const a=await cas.put(new TextEncoder().encode("hello"));const b=await cas.put(new TextEncoder().encode("hello"));assert.equal(a.key,b.key);assert.equal(await cas.verify(a.digest),true)});
